### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by DarkCrystal111** [x11-repo/hack-tools#1]
Пытаюсь запустить HackTools.py но выдает:
`Traceback (most recent call last):
  File "HackTools.py", line 36, in <module>
    code1()
  File "HackTools.py", line 28, in code1
    from core import exe
ImportError: cannot import name 'exe' from 'core' (/usr/local/lib/python3.8/dist-packages/xsser-1.8.3-py3.8.egg/core/__init__.py)
`

**Comment by DarkCrystal111** [comment]
Решил проблему созданием файла `__init__.py` в директории core

**Comment by x11-repo** [comment]
Посмотрю что вызывает ошибку. Постораюсь исправить

чт, 23 апр. 2020 г., 9:02 DarkCrystal111 <notifications@github.com>:
